# Generated by Django 4.0.5 on 2022-12-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idAgenda', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('hora', models.CharField(max_length=6)),
                ('rutmedico', models.CharField(max_length=20)),
            ],
        ),
    ]
