# Generated by Django 4.0.5 on 2022-12-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarioBase',
            fields=[
                ('idCalendarioBase', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HoraMedica',
            fields=[
                ('idhoraMedica', models.AutoField(primary_key=True, serialize=False)),
                ('Hora', models.CharField(max_length=6)),
                ('dia', models.DateField()),
                ('rut', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('idInforme', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('contenido', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fechaNacimiento', models.DateField()),
                ('correo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('rut', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('rol', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fechaNacimiento', models.DateField()),
                ('correo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('rol', models.CharField(max_length=20)),
            ],
        ),
    ]
