# Generated by Django 4.0.5 on 2022-12-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cajero_calendariobase_horamedica_informe_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='idPago',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
